# Site settings
title: "Luigi's Blog"
description: "Thoughts on AI, Data Science, and Technology"
url: "https://lcorreale.github.io"
baseurl: ""  # For user/organization pages, keep this empty

# Author settings
author:
  name: "Luigi's Blog"
  email: "paistos@bluewin.ch"

# Build settings
markdown: kramdown
<<<<<<< HEAD

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


=======
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
>>>>>>> aa3b28db3090bf047a6c5cb6651daba5cb09b6e2
# Permalinks
permalink: /:year/:month/:day/:title/

# Social links (optional)
twitter_username: tba
github_username: lcorreale

# Exclude these files/folders from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X
