# Site settings
title: "Luigi's Blog"
description: "Thoughts on AI, Data Science, and Technology"
url: "https://lcorreale.github.io"
baseurl: ""  # For user/organization pages, keep this empty

# Author settings
author:
  name: "Luigi's Blog"
  email: "your.email@example.com"

# Build settings
markdown: kramdown
theme: minima  # Or another supported theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks
permalink: /:year/:month/:day/:title/

# Social links (optional)
twitter_username: yourtwitter
github_username: lcorreale

# Exclude these files/folders from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X
