title: "Luigi's Blog"
description: "Thoughts on AI, Data Science, and Technology"
url: "https://lcorreale.github.io"
baseurl: ""
repository: lcorreale/lcorreale.github.io  # <-- add this line

remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: kramdown
permalink: /:year/:month/:day/:title/
